### ISSUE TITLE
Be able to accept special chars

### ISSUE THREAD

**Issue by gabrielfurini** [gabrielfurini/morsee#1]
For now the library only has ordinal letters and digits into its dictionary. Make it able to handle special characters too

**Comment by vinyvicente** [comment]
Have sure?

Maybe just to translate "áááááééééíííí" before encode.

Has morse code to special chars?

**Comment by evansantos** [comment]
I don't know if I should open a new issue, but enter wouldn't add a slash or something like because when you get a text instead of a quote it's get all mess up

https://9o8x7rwor4.codesandbox.io/

**Comment by gabrielfurini** [comment]
@vinyvicente, I expressed myself erroneously. I was referring to special chars for punctuation not accentuation. These ones definitely should be represented and they gonna be there soon, in the next version probably.

**Comment by gabrielfurini** [comment]
@evansantos you're definitely right about a new line representation. Gonna research the right way of doing it. BTW I've just opened a new issue (https://github.com/gabrielfurini/morsee/issues/2). Thanks for reporting it 🙏
