### ISSUE TITLE
A way to represent new lines

### ISSUE THREAD

**Issue by gabrielfurini** [gabrielfurini/morsee#2]
I don't know if I should open a new issue, but enter wouldn't add a slash or something like because when you get a text instead of a quote it's get all mess up

https://9o8x7rwor4.codesandbox.io/

_Originally posted by @evansantos in https://github.com/gabrielfurini/morsee/issues/1#issuecomment-450444746_

**Comment by gabrielfurini** [comment]
@evansantos hey dude. I was researching the right way to represent new lines and concluded that since morse code was designed to represent words and sentences not visually but in sounds, it doesn't have a proper way to solve your UI issue by it's conception.

When encoding from latin to morse code, new lines are represented by `.-.-`. Which means if you wanna represent this line break visually, you gonna need to do it directly on your UI implementation.

**Comment by evansantos** [comment]
@gabrielfurini thank you for your answer, later I wrote this comment I was figuring out code morse wasn't supposed to be more than a few words, but thanks anyway I'll add this to my UI
